[project]
name = "trading-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "gymnasium>=1.1.1",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "ray[rllib]>=2.49.1",
    "torch>=2.8.0",
]
